return {
    Smacks = 0,
    SmackerName = "Default",
    BoughtSmackers = {
        "Default"
    },
    Settings = {
        ["Global Shadows"] = true,
        ["Night Mode"] = false,
        ["Camera Shake"] = true,
        ["Attack Hitboxes"] = false,
        ["Motion Blur"] = false,
        ["Master Volume"] = 100,
        ["Music Volume"] = 100,
        ["SFX Volume"] = 100,
        ["AFK Mode"] = false
    }
}