return {
    {
        SmackerName = "Default",
        Shop = {
            Price = 0
        },
        Smack = {
            Damage = 7,
            KnockbackSpeed = 30,
            KnockbackUp = 15,
            AnimationSpeed = 1,
        },
        Attack = {
            AttackName = "Smash",
            AttackDuration = 2,
            AttackDebounce = 10,
        }
    },
    {
        SmackerName = "Extended",
        Shop = {
            Price = 10
        },
        Smack = {
            Damage = 6,
            KnockbackSpeed = 45,
            KnockbackUp = 20,
            AnimationSpeed = 1,
        },
        Attack = {
            AttackName = "Long Smash",
            AttackDuration = 2,
            AttackDebounce = 20,
        }
    },
    {
        SmackerName = "Fire",
        Shop = {
            Price = 25
        },
        Smack = {
            Damage = 7,
            KnockbackSpeed = 30,
            KnockbackUp = 15,
            AnimationSpeed = 1,
        },
        Attack = {
            AttackName = "Too Hot",
            AttackDuration = 2,
            AttackDebounce = 15,
        }
    },
    {
        SmackerName = "Ice",
        Shop = {
            Price = 50
        },
        Smack = {
            Damage = 7,
            KnockbackSpeed = 30,
            KnockbackUp = 15,
            AnimationSpeed = 1,
        },
        Attack = {
            AttackName = "Too Cold",
            AttackDuration = 2,
            AttackDebounce = 15,
        }
    },
    {
        SmackerName = "Spear",
        Shop = {
            Price = 100
        },
        Smack = {
            Damage = 7,
            KnockbackSpeed = 30,
            KnockbackUp = 15,
            AnimationSpeed = 1,
        },
        Attack = {
            AttackName = "Throw",
            AttackDuration = 1,
            AttackDebounce = 5,
        }
    },
    {
        SmackerName = "Dash",
        Shop = {
            Price = 250
        },
        Smack = {
            Damage = 8,
            KnockbackSpeed = 30,
            KnockbackUp = 15,
            AnimationSpeed = 1,
        },
        Attack = {
            AttackName = "Dash",
            AttackDuration = .5,
            AttackDebounce = 2,
        }
    },
    {
        SmackerName = "Stealth",
        Shop = {
            Price = 500
        },
        Smack = {
            Damage = 8,
            KnockbackSpeed = 30,
            KnockbackUp = 15,
            AnimationSpeed = 1,
        },
        Attack = {
            AttackName = "Camouflage",
            AttackDuration = .5,
            AttackDebounce = 15,
        }
    },
    {
        SmackerName = "Landmine",
        Shop = {
            Price = 1000
        },
        Smack = {
            Damage = 7,
            KnockbackSpeed = 30,
            KnockbackUp = 15,
            AnimationSpeed = 1,
        },
        Attack = {
            AttackName = "Explode",
            AttackDuration = .5,
            AttackDebounce = 25,
        }
    },
}